namespace Frontends.Models.RocketLauncher
{
    public enum RlMediaType
    {
        Artwork,
        Backgrounds,
        Bezels,
        Cards,
        Controller,
        Cursors,
        Developer,    
        Fade,
        Fonts,
        Genre,
        Guides,
        Keymapper,
        Logos,
        Manuals,        
        MovesList,
        MultiGame,
        Music,
        Publisher,
        Rating,
        SavedGames,
        Sounds,
        Videos,
        Year
    }
}
